[project]
name = "FinMCP"
version = "0.1.0"
description = "financial LLM system"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crawl4ai>=0.5.0.post8",
    "fastapi>=0.115.12",
    "mcp>=1.6.0",
    "openai>=1.73.0",
    "sse-starlette>=2.2.1",
    "starlette>=0.46.1",
]
